<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 介绍线性混合效应模型 | 学习统计模型——通过R模拟(施工中)</title>
  <meta name="description" content="5 介绍线性混合效应模型 | 学习统计模型——通过R模拟(施工中)" />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="5 介绍线性混合效应模型 | 学习统计模型——通过R模拟(施工中)" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 介绍线性混合效应模型 | 学习统计模型——通过R模拟(施工中)" />
  
  
  

<meta name="author" content="周博霖" />


<meta name="date" content="2024-06-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="交互效应.html"/>
<link rel="next" href="参考文献.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  jax: ["input/TeX","output/SVG"],
  extensions: ["tex2jax.js","MathMenu.js","MathZoom.js"],
  TeX: {
    extensions: ["AMSmath.js","AMSsymbols.js","noErrors.js","noUndefined.js"]
  }
});
</script>
<script type="text/javascript"
   src="../../../MathJax/MathJax.js">
</script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />
<link rel="stylesheet" href="include/webex.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>概述</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#译者按"><i class="fa fa-check"></i>译者按</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#如何引用本书"><i class="fa fa-check"></i>如何引用本书</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#发现问题"><i class="fa fa-check"></i>发现问题？</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#教育者需知"><i class="fa fa-check"></i>教育者需知</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="前言.html"><a href="前言.html"><i class="fa fa-check"></i><b>1</b> 前言</a>
<ul>
<li class="chapter" data-level="1.1" data-path="前言.html"><a href="前言.html#课程目的"><i class="fa fa-check"></i><b>1.1</b> 课程目的</a></li>
<li class="chapter" data-level="1.2" data-path="前言.html"><a href="前言.html#广义线性混合效应模型generalized-linear-mixed-effects-models-glmms"><i class="fa fa-check"></i><b>1.2</b> 广义线性混合效应模型(Generalized Linear Mixed-Effects Models, GLMMs)</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="前言.html"><a href="前言.html#线性模型"><i class="fa fa-check"></i><b>1.2.1</b> 线性模型</a></li>
<li class="chapter" data-level="1.2.2" data-path="前言.html"><a href="前言.html#混合模型"><i class="fa fa-check"></i><b>1.2.2</b> 混合模型</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="前言.html"><a href="前言.html#关于可重复性的说明"><i class="fa fa-check"></i><b>1.3</b> 关于可重复性的说明</a></li>
<li class="chapter" data-level="1.4" data-path="前言.html"><a href="前言.html#基于模拟的方法"><i class="fa fa-check"></i><b>1.4</b> 基于模拟的方法</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="相关和回归.html"><a href="相关和回归.html"><i class="fa fa-check"></i><b>2</b> 相关和回归</a>
<ul>
<li class="chapter" data-level="2.1" data-path="相关和回归.html"><a href="相关和回归.html#相关矩阵correlation-matrices"><i class="fa fa-check"></i><b>2.1</b> 相关矩阵(Correlation matrices)</a></li>
<li class="chapter" data-level="2.2" data-path="相关和回归.html"><a href="相关和回归.html#模拟二元数据"><i class="fa fa-check"></i><b>2.2</b> 模拟二元数据</a></li>
<li class="chapter" data-level="2.3" data-path="相关和回归.html"><a href="相关和回归.html#相关和回归的关系"><i class="fa fa-check"></i><b>2.3</b> 相关和回归的关系</a></li>
<li class="chapter" data-level="2.4" data-path="相关和回归.html"><a href="相关和回归.html#练习"><i class="fa fa-check"></i><b>2.4</b> 练习</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="多元回归.html"><a href="多元回归.html"><i class="fa fa-check"></i><b>3</b> 多元回归</a>
<ul>
<li class="chapter" data-level="3.1" data-path="多元回归.html"><a href="多元回归.html#一个例子如何在统计学上取得好成绩"><i class="fa fa-check"></i><b>3.1</b> 一个例子：如何在统计学上取得好成绩</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="多元回归.html"><a href="多元回归.html#数据导入和可视化"><i class="fa fa-check"></i><b>3.1.1</b> 数据导入和可视化</a></li>
<li class="chapter" data-level="3.1.2" data-path="多元回归.html"><a href="多元回归.html#估计和解释"><i class="fa fa-check"></i><b>3.1.2</b> 估计和解释</a></li>
<li class="chapter" data-level="3.1.3" data-path="多元回归.html"><a href="多元回归.html#使用predict通过线性模型进行预测"><i class="fa fa-check"></i><b>3.1.3</b> 使用<code>predict()</code>通过线性模型进行预测</a></li>
<li class="chapter" data-level="3.1.4" data-path="多元回归.html"><a href="多元回归.html#偏效应可视化"><i class="fa fa-check"></i><b>3.1.4</b> 偏效应可视化</a></li>
<li class="chapter" data-level="3.1.5" data-path="多元回归.html"><a href="多元回归.html#标准化系数"><i class="fa fa-check"></i><b>3.1.5</b> 标准化系数</a></li>
<li class="chapter" data-level="3.1.6" data-path="多元回归.html"><a href="多元回归.html#模型比较"><i class="fa fa-check"></i><b>3.1.6</b> 模型比较</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="多元回归.html"><a href="多元回归.html#处理分类预测变量"><i class="fa fa-check"></i><b>3.2</b> 处理分类预测变量</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="多元回归.html"><a href="多元回归.html#虚拟编码又称处理编码"><i class="fa fa-check"></i><b>3.2.1</b> 虚拟编码(又称“处理”编码)</a></li>
<li class="chapter" data-level="3.2.2" data-path="多元回归.html"><a href="多元回归.html#当k-2时的虚拟编码"><i class="fa fa-check"></i><b>3.2.2</b> 当<span class="math inline">\(k &gt; 2\)</span>时的虚拟编码</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="多元回归.html"><a href="多元回归.html#多元回归和单因素方差分析one-way-anova的等价性"><i class="fa fa-check"></i><b>3.3</b> 多元回归和单因素方差分析(one-way ANOVA)的等价性</a></li>
<li class="chapter" data-level="3.4" data-path="多元回归.html"><a href="多元回归.html#练习答案"><i class="fa fa-check"></i><b>3.4</b> 练习答案</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="交互效应.html"><a href="交互效应.html"><i class="fa fa-check"></i><b>4</b> 交互效应</a>
<ul>
<li class="chapter" data-level="4.1" data-path="交互效应.html"><a href="交互效应.html#cont-by-cat"><i class="fa fa-check"></i><b>4.1</b> 连续变量-分类变量交互效应</a></li>
<li class="chapter" data-level="4.2" data-path="交互效应.html"><a href="交互效应.html#分类变量-分类变量交互效应"><i class="fa fa-check"></i><b>4.2</b> 分类变量-分类变量交互效应</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="交互效应.html"><a href="交互效应.html#认知治疗与药物治疗对情绪的影响"><i class="fa fa-check"></i><b>4.2.1</b> 认知治疗与药物治疗对情绪的影响</a></li>
<li class="chapter" data-level="4.2.2" data-path="交互效应.html"><a href="交互效应.html#因子设计中的效应"><i class="fa fa-check"></i><b>4.2.2</b> 因子设计中的效应</a></li>
<li class="chapter" data-level="4.2.3" data-path="交互效应.html"><a href="交互效应.html#高阶设计higher-order-designs"><i class="fa fa-check"></i><b>4.2.3</b> 高阶设计(Higher-order designs)</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="交互效应.html"><a href="交互效应.html#用于因子设计的glm"><i class="fa fa-check"></i><b>4.3</b> 用于因子设计的GLM</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="交互效应.html"><a href="交互效应.html#估计方程estimation-equations"><i class="fa fa-check"></i><b>4.3.1</b> 估计方程(estimation equations)</a></li>
<li class="chapter" data-level="4.3.2" data-path="交互效应.html"><a href="交互效应.html#因子设计app"><i class="fa fa-check"></i><b>4.3.2</b> 因子设计App</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="交互效应.html"><a href="交互效应.html#在因子设计中对分类预测因子进行编码"><i class="fa fa-check"></i><b>4.4</b> 在因子设计中对分类预测因子进行编码</a></li>
<li class="chapter" data-level="4.5" data-path="交互效应.html"><a href="交互效应.html#分类变量的编码方案"><i class="fa fa-check"></i><b>4.5</b> 分类变量的编码方案</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="交互效应.html"><a href="交互效应.html#简单效应-vs.-主效应"><i class="fa fa-check"></i><b>4.5.1</b> 简单效应 vs. 主效应</a></li>
<li class="chapter" data-level="4.5.2" data-path="交互效应.html"><a href="交互效应.html#主要编码方案"><i class="fa fa-check"></i><b>4.5.2</b> 主要编码方案</a></li>
<li class="chapter" data-level="4.5.3" data-path="交互效应.html"><a href="交互效应.html#超过2水平的因子呢"><i class="fa fa-check"></i><b>4.5.3</b> 超过2水平的因子呢？</a></li>
<li class="chapter" data-level="4.5.4" data-path="交互效应.html"><a href="交互效应.html#举例3水平因子"><i class="fa fa-check"></i><b>4.5.4</b> 举例：3水平因子</a></li>
<li class="chapter" data-level="4.5.5" data-path="交互效应.html"><a href="交互效应.html#如何创建你自己的数值型预测变量"><i class="fa fa-check"></i><b>4.5.5</b> 如何创建你自己的数值型预测变量</a></li>
<li class="chapter" data-level="4.5.6" data-path="交互效应.html"><a href="交互效应.html#小结"><i class="fa fa-check"></i><b>4.5.6</b> 小结</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="介绍线性混合效应模型.html"><a href="介绍线性混合效应模型.html"><i class="fa fa-check"></i><b>5</b> 介绍线性混合效应模型</a>
<ul>
<li class="chapter" data-level="5.1" data-path="介绍线性混合效应模型.html"><a href="介绍线性混合效应模型.html#多层数据建模"><i class="fa fa-check"></i><b>5.1</b> 多层数据建模</a></li>
<li class="chapter" data-level="5.2" data-path="介绍线性混合效应模型.html"><a href="介绍线性混合效应模型.html#如何对这些数据进行建模"><i class="fa fa-check"></i><b>5.2</b> 如何对这些数据进行建模</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="介绍线性混合效应模型.html"><a href="介绍线性混合效应模型.html#完全混合一刀切"><i class="fa fa-check"></i><b>5.2.1</b> 完全混合：一刀切</a></li>
<li class="chapter" data-level="5.2.2" data-path="介绍线性混合效应模型.html"><a href="介绍线性混合效应模型.html#不混合"><i class="fa fa-check"></i><b>5.2.2</b> 不混合</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="介绍线性混合效应模型.html"><a href="介绍线性混合效应模型.html#使用混合效果模型的部分混合"><i class="fa fa-check"></i><b>5.3</b> 使用混合效果模型的部分混合</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="参考文献.html"><a href="参考文献.html"><i class="fa fa-check"></i>参考文献</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">学习统计模型——通过R模拟(施工中)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="介绍线性混合效应模型" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">5</span> 介绍线性混合效应模型<a href="介绍线性混合效应模型.html#介绍线性混合效应模型" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="多层数据建模" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> 多层数据建模<a href="介绍线性混合效应模型.html#多层数据建模" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="bluebox">
<p>本章中的一些观点来自 <span class="citation">McElreath (<a href="#ref-McElreath_2020">2020</a>)</span> 的<a href="https://xcelab.net/rm/statistical-rethinking/">《Statistical Rethinking》</a>，还广泛借鉴了Tristan Mahr关于部分混合(partial pooling)的出色<a href="https://www.tjmahr.com/plotting-partial-pooling-in-mixed-effects-models/">博客</a>。</p>
</div>
<p>在本章中，我们将使用一些来自研究睡眠剥夺对心理运动能力(psychomotor performance)影响的真实数据<span class="citation">(<a href="#ref-Belenky_et_al_2003">Belenky et al., 2003</a>)</span>。该研究的数据包含在R的<code>lme4</code>包中的内置数据集<code>sleepstudy</code>中<span class="citation">(<a href="#ref-Bates_et_al_2015">Bates et al., 2015</a>)</span>。</p>
<p>让我们从查看<code>sleepstudy</code>数据集的文档开始。加载<strong><code>lme4</code></strong>包后，你可以在控制台中输入<code>?sleepstudy</code>来访问文档。</p>
<pre><code>注：这是对数据集文档的中文翻译
sleepstudy                package:lme4                 R Documentation

睡眠剥夺研究中的反应时

描述：

     一项睡眠剥夺研究中，被试每天的平均反应时(以毫秒为单位)。
    
     第0-1天为适应和训练阶段(T1/T2)，第2天为基线(B)；睡眠剥夺从第2天开始。
    
格式：

     一个包含180个观测结果的数据框，其中包含以下3个变量：
    
     Reaction：平均反应时(毫秒)
    
     Days：睡眠剥夺的天数
    
     Subject：进行观测的被试编号

详细信息：

     这些数据来自Belenky et al.(2003)描述的研究，针对的是最严重的睡
     眠剥夺组(每天仅睡3小时)和研究的前10天，直到恢复期。原始研究分析
     了速度(1/反应时)，并将天数作为分类而非连续预测变量进行处理。

参考文献：

     Gregory Belenky, Nancy J. Wesensten, David R. Thorne, Maria L.
     Thomas, Helen C. Sing, Daniel P. Redmond, Michael B. Russo and
     Thomas J. Balkin (2003) Patterns of performance degradation and
     restoration during sleep restriction and subsequent recovery: a
     sleep dose-response study. _Journal of Sleep Research_ *12*, 1-12.</code></pre>
<p>这些数据符合我们对多层数据的定义，因为在十天内对同一被试的同一因变量(平均反应时)进行了重复测量。这种类型的多层数据在心理学中非常常见。不幸的是，大多数心理学课程常用的统计教材对多层数据的讨论是不充分的，通常只涉及配对样本t检验和重复测量ANOVA。<code>sleepstudy</code>数据集很有趣，因为它是多层的，但有一个连续的预测变量，因此不适合t检验或ANOVA，因为这两种方法都是针对分类预测变量的。有方法可以让数据适应其中一个框架，但会丢失信息或可能违反假设。</p>
<p>遗憾的是，心理学专业的学生并没有真正学会如何分析多层数据。想想你最近读过的心理学或神经科学的研究。有多少研究是对每个被试只测量一次因变量？很少，如果有的话。几乎所有研究都进行了多次测量，因为以下一种或多种原因：(1)研究者在被试内设计中跨因子多水平测量同一被试；(2)他们有兴趣评估随时间的变化；或(3)他们在测量对多种刺激的反应。多层数据如此常见，以至于多层分析应该作为心理学中的<strong>默认</strong>方法来教授。学习多层分析可能具有挑战性，但你已经通过学习相关和回归掌握了大部分所需的知识。你会发现它只是简单回归的扩展。</p>
<p>让我们更详细地看看<code>sleepstudy</code>数据。该数据集包含来自三小时睡眠情况下的十八位被试。在为期十天的时间里，被试每天进行十分钟的“心理运动警觉性测试(psychomotor vigilance test)”，在每次出现刺激时尽快按下按钮。数据集中的因变量是被试在当天任务中的平均反应时(RT)。</p>
<p>开始分析的一个好方法是绘制数据图。下面是一个被试的数据。</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="介绍线性混合效应模型.html#cb116-1" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb116-2"><a href="介绍线性混合效应模型.html#cb116-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb116-3"><a href="介绍线性混合效应模型.html#cb116-3" tabindex="-1"></a></span>
<span id="cb116-4"><a href="介绍线性混合效应模型.html#cb116-4" tabindex="-1"></a>just_308 <span class="ot">&lt;-</span> sleepstudy <span class="sc">%&gt;%</span></span>
<span id="cb116-5"><a href="介绍线性混合效应模型.html#cb116-5" tabindex="-1"></a>  <span class="fu">filter</span>(Subject <span class="sc">==</span> <span class="st">&quot;308&quot;</span>)</span>
<span id="cb116-6"><a href="介绍线性混合效应模型.html#cb116-6" tabindex="-1"></a></span>
<span id="cb116-7"><a href="介绍线性混合效应模型.html#cb116-7" tabindex="-1"></a><span class="fu">ggplot</span>(just_308, <span class="fu">aes</span>(<span class="at">x =</span> Days, <span class="at">y =</span> Reaction)) <span class="sc">+</span></span>
<span id="cb116-8"><a href="介绍线性混合效应模型.html#cb116-8" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb116-9"><a href="介绍线性混合效应模型.html#cb116-9" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">9</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:one-subject"></span>
<img src="05-%E4%BB%8B%E7%BB%8D%E7%BA%BF%E6%80%A7%E6%B7%B7%E5%90%88%E6%95%88%E5%BA%94%E6%A8%A1%E5%9E%8B_files/figure-html/one-subject-1.png" alt="*Belenky et al.(2003)中单个被试的数据*" width="50%" />
<p class="caption">
图5.1: <em>Belenky et al.(2003)中单个被试的数据</em>
</p>
</div>
<div class="purplebox">
<p><strong>练习</strong></p>
<p>使用<code>ggplot</code>重现下面的图，这包含了所有18个被试。</p>
<div class="figure"><span style="display:block;" id="fig:plot-solution0"></span>
<img src="05-%E4%BB%8B%E7%BB%8D%E7%BA%BF%E6%80%A7%E6%B7%B7%E5%90%88%E6%95%88%E5%BA%94%E6%A8%A1%E5%9E%8B_files/figure-html/plot-solution0-1.png" alt="*Belenky et al.(2003)中的数据*" width="672" />
<p class="caption">
图5.2: <em>Belenky et al.(2003)中的数据</em>
</p>
</div>
<p>从第2天开始到第10天，RT似乎随着睡眠剥夺天数的增加而增加。</p>
<div class="webex-solution">
<button>
请提示
</button>
<p>上面给出了绘制单个被试数据的代码。通过去掉<code>filter()</code>语句并添加以<code>facet_</code>开头的<em><code>ggplot2</code></em>函数，将此代码改为显示所有被试的数据。</p>
</div>
<div class="webex-solution">
<button>
展示答案
</button>
<p>和上面一样，只是你要增加一行：<code>facet_wrap(~Subject)</code></p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="介绍线性混合效应模型.html#cb117-1" tabindex="-1"></a><span class="fu">ggplot</span>(sleepstudy, <span class="fu">aes</span>(<span class="at">x =</span> Days, <span class="at">y =</span> Reaction)) <span class="sc">+</span></span>
<span id="cb117-2"><a href="介绍线性混合效应模型.html#cb117-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb117-3"><a href="介绍线性混合效应模型.html#cb117-3" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">9</span>) <span class="sc">+</span></span>
<span id="cb117-4"><a href="介绍线性混合效应模型.html#cb117-4" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Subject)</span></code></pre></div>
</div>
</div>
</div>
<div id="如何对这些数据进行建模" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> 如何对这些数据进行建模<a href="介绍线性混合效应模型.html#如何对这些数据进行建模" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>要合理地对数据进行建模，我们首先需要了解更多关于设计的信息 <span class="citation">Belenky et al. (<a href="#ref-Belenky_et_al_2003">2003</a>)</span> 在他们的研究中是这样描述的(p. 2)：</p>
<blockquote>
<p>前3天(T1、T2和B)是适应和训练(T1和T2)以及基线(B)，被试要求从23:00到07:00上床睡觉[在床时间(time in bed，TIB)为8小时]。在第3天(B)，进行了基线测量。从第4天开始，连续7天(E1-E7)，被试处于4种睡眠条件之一[TIB为9小时(22:00–07:00)，TIB为7小时(24:00–07:00)，TIB为5小时(02:00–07:00)或TIB为3小时(04:00–07:00)]，实际上是一种睡眠延长条件和三种睡眠限制条件。</p>
</blockquote>
<p>从第3天之后的第1晚开始，有7晚的睡眠限制。前2天，编码为<code>0</code>、<code>1</code>，是适应(adaptation)和训练(training)。编码为<code>2</code>的那天是进行基线测量的时间，应该是我们分析开始的地方。如果我们将<code>0</code>和<code>1</code>两天包含在我们的分析中，可能会偏倚(bias)我们的结果，因为前两天的任何表现变化都与训练有关，而不是与睡眠限制有关。</p>
<div class="purplebox">
<p><strong><em>练习</em></strong></p>
<p>从数据集中删除<code>Days</code>编码为<code>0</code>或<code>1</code>的观察值，然后根据<code>Days</code>变量创建一个新的变量<code>days_deprived</code>，使序列从第2天开始，第2天重新编码为第0天，第3天为第1天，第4天为第2天，依此类推。这个新变量现在追踪睡眠剥夺的天数。将新表存储为<code>sleep2</code>。</p>
<div class="webex-solution">
<button>
展开答案
</button>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="介绍线性混合效应模型.html#cb118-1" tabindex="-1"></a>sleep2 <span class="ot">&lt;-</span> sleepstudy <span class="sc">%&gt;%</span></span>
<span id="cb118-2"><a href="介绍线性混合效应模型.html#cb118-2" tabindex="-1"></a>  <span class="fu">filter</span>(Days <span class="sc">&gt;=</span> 2L) <span class="sc">%&gt;%</span></span>
<span id="cb118-3"><a href="介绍线性混合效应模型.html#cb118-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">days_deprived =</span> Days <span class="sc">-</span> 2L)</span></code></pre></div>
<p>仔细检查代码是否按预期工作总是一个好主意。首先，看看它：</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="介绍线性混合效应模型.html#cb119-1" tabindex="-1"></a><span class="fu">head</span>(sleep2)</span></code></pre></div>
<pre><code>##   Reaction Days Subject days_deprived
## 1 250.8006    2     308             0
## 2 321.4398    3     308             1
## 3 356.8519    4     308             2
## 4 414.6901    5     308             3
## 5 382.2038    6     308             4
## 6 290.1486    7     308             5</code></pre>
<p>检查<code>Days</code>和<code>days_deprivation</code>是否匹配。</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="介绍线性混合效应模型.html#cb121-1" tabindex="-1"></a>sleep2 <span class="sc">%&gt;%</span></span>
<span id="cb121-2"><a href="介绍线性混合效应模型.html#cb121-2" tabindex="-1"></a>  <span class="fu">count</span>(days_deprived, Days)</span></code></pre></div>
<pre><code>##   days_deprived Days  n
## 1             0    2 18
## 2             1    3 18
## 3             2    4 18
## 4             3    5 18
## 5             4    6 18
## 6             5    7 18
## 7             6    8 18
## 8             7    9 18</code></pre>
<p>看起来很好. 请注意，由<code>count()</code>生成的变量<code>n</code>会告诉你<code>Days</code>和<code>days_deprivation</code>的每个唯一组合有多少行。在这种情况下有18行，每个被试1行。</p>
</div>
</div>
<p>现在让我们重新绘制数据，只查看从第0天到第7天的这8个数据点。我们已经从上面的代码中复制了代码，将<code>sleepstudy</code>替换为<code>sleep2</code>，并使用<code>days_deprived</code>作为我们的<code>x</code>变量。</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="介绍线性混合效应模型.html#cb123-1" tabindex="-1"></a><span class="fu">ggplot</span>(sleep2, <span class="fu">aes</span>(<span class="at">x =</span> days_deprived, <span class="at">y =</span> Reaction)) <span class="sc">+</span></span>
<span id="cb123-2"><a href="介绍线性混合效应模型.html#cb123-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb123-3"><a href="介绍线性混合效应模型.html#cb123-3" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">7</span>) <span class="sc">+</span></span>
<span id="cb123-4"><a href="介绍线性混合效应模型.html#cb123-4" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Subject) <span class="sc">+</span></span>
<span id="cb123-5"><a href="介绍线性混合效应模型.html#cb123-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;反应时&quot;</span>, <span class="at">x =</span> <span class="st">&quot;睡眠剥夺的天数(0 = 基线)&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:plot-solution2"></span>
<img src="05-%E4%BB%8B%E7%BB%8D%E7%BA%BF%E6%80%A7%E6%B7%B7%E5%90%88%E6%95%88%E5%BA%94%E6%A8%A1%E5%9E%8B_files/figure-html/plot-solution2-1.png" alt="*数据来自Belenky et al.(2003)，显示了基线(0天)和每天睡眠剥夺后的反应时*" width="672" />
<p class="caption">
图5.3: <em>数据来自Belenky et al.(2003)，显示了基线(0天)和每天睡眠剥夺后的反应时</em>
</p>
</div>
<p>请稍作思考，我们如何对<code>days_deprived</code>和<code>Reaction</code>之间的关系建模。随着睡眠剥夺的增加，反应时间是增加还是减少？这种关系大致稳定还是随时间变化？</p>
<p>除了一个例外(335号被试)，看起来反应时随着睡眠剥夺的增加而增加。看起来我们可以对每位被试的数据拟合一条直线。回想一下，一条直线的一般方程形式为<strong>y = y轴截距 + 斜率 <span class="math inline">\(\times\)</span> x</strong>。在回归分析中，我们通常用以下公式表示线性关系：</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1 X\]</span></p>
<p>其中<span class="math inline">\(\beta_0\)</span>是y轴截距，<span class="math inline">\(\beta_1\)</span>是斜率，这些参数都是我们从数据中估计而来的。</p>
<p>这些线的截距(剥夺睡眠开始前第0天的平均RT)和斜率(每增加一天的睡眠剥夺后RT的变化)都不同。但我们应该为每个被试拟合同一条线吗？还是每个被试拟合完全不同的线？或者介于两者之间的某种情况？</p>
<p>让我们首先考虑可能用到的三种不同方法。根据McElreath的说法，我们将这些方法称为<strong>完全混合(complete pooling)</strong>、<strong>不混合(no pooling)</strong>和<strong>部分混合(partial pooling)</strong>。</p>
<div id="完全混合一刀切" class="section level3 hasAnchor" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> 完全混合：一刀切<a href="介绍线性混合效应模型.html#完全混合一刀切" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>完全混合</strong>是一种“一刀切”模型：它为整个数据集估计单一的截距和斜率，忽略了不同被试在截距或斜率上可能存在的差异。如果这听起来像是一种糟糕的方法，那确实是对的；但你知道这一点是因为你已经可视化了数据，并注意到每个参与者的模式似乎需要不同的y轴截距和斜率值。</p>
<p>拟合出一条线称为“完全混合”方法，因为我们将所有被试的数据混合在一起，得到总体截距和斜率的单一估计。该方法的广义线性模型(GLM)简单地表示为：</p>
<p><span class="math display">\[Y_{sd} = \beta_0 + \beta_1 X_{sd} + e_{sd}\]</span></p>
<p><span class="math display">\[e_{sd} \sim N\left(0, \sigma^2\right)\]</span></p>
<p>其中<span class="math inline">\(Y_{sd}\)</span>是被试<span class="math inline">\(s\)</span>在第<span class="math inline">\(d\)</span>天的平均反应时，<span class="math inline">\(X_{sd}\)</span>是与该情况相关的<code>days_deprived</code>值(0-7)，<span class="math inline">\(e_{sd}\)</span>是误差。</p>
<p>我们可以在R中用<code>lm()</code>函数拟合一个这样的模型，如下：</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="介绍线性混合效应模型.html#cb124-1" tabindex="-1"></a>cp_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Reaction <span class="sc">~</span> days_deprived, sleep2)</span>
<span id="cb124-2"><a href="介绍线性混合效应模型.html#cb124-2" tabindex="-1"></a></span>
<span id="cb124-3"><a href="介绍线性混合效应模型.html#cb124-3" tabindex="-1"></a><span class="fu">summary</span>(cp_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Reaction ~ days_deprived, data = sleep2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -112.284  -26.732    2.143   27.734  140.453 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    267.967      7.737  34.633  &lt; 2e-16 ***
## days_deprived   11.435      1.850   6.183 6.32e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 50.85 on 142 degrees of freedom
## Multiple R-squared:  0.2121, Adjusted R-squared:  0.2066 
## F-statistic: 38.23 on 1 and 142 DF,  p-value: 6.316e-09</code></pre>
<p>根据这个模型，第0天的预测平均反应时约为268毫秒，随着剥夺天数的增加，每天的反应时平均增加约11毫秒。然而，我们不能相信回归系数的标准误，因为我们假设所有的观测值都是独立的(严格来说是残差独立)。但我们可以很确定这是一个糟糕的假设。</p>
<p>让我们把模型预测值添加到我们之前创建的图中。我们可以使用<code>geom_abline()</code>来做到这一点，指定截距和斜率为模型拟合的回归系数<code>coef(cp_model)</code>，该函数返回一个包含截距和斜率两个元素的向量。</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="介绍线性混合效应模型.html#cb126-1" tabindex="-1"></a><span class="fu">coef</span>(cp_model)</span></code></pre></div>
<pre><code>##   (Intercept) days_deprived 
##     267.96742      11.43543</code></pre>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="介绍线性混合效应模型.html#cb128-1" tabindex="-1"></a><span class="fu">ggplot</span>(sleep2, <span class="fu">aes</span>(<span class="at">x =</span> days_deprived, <span class="at">y =</span> Reaction)) <span class="sc">+</span></span>
<span id="cb128-2"><a href="介绍线性混合效应模型.html#cb128-2" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fu">coef</span>(cp_model)[<span class="dv">1</span>],</span>
<span id="cb128-3"><a href="介绍线性混合效应模型.html#cb128-3" tabindex="-1"></a>              <span class="at">slope =</span> <span class="fu">coef</span>(cp_model)[<span class="dv">2</span>],</span>
<span id="cb128-4"><a href="介绍线性混合效应模型.html#cb128-4" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">&#39;blue&#39;</span>) <span class="sc">+</span></span>
<span id="cb128-5"><a href="介绍线性混合效应模型.html#cb128-5" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb128-6"><a href="介绍线性混合效应模型.html#cb128-6" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">7</span>) <span class="sc">+</span></span>
<span id="cb128-7"><a href="介绍线性混合效应模型.html#cb128-7" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Subject) <span class="sc">+</span></span>
<span id="cb128-8"><a href="介绍线性混合效应模型.html#cb128-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;反应时&quot;</span>, <span class="at">x =</span> <span class="st">&quot;睡眠剥夺的天数(0 = 基线)&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:cp-model-plot"></span>
<img src="05-%E4%BB%8B%E7%BB%8D%E7%BA%BF%E6%80%A7%E6%B7%B7%E5%90%88%E6%95%88%E5%BA%94%E6%A8%A1%E5%9E%8B_files/figure-html/cp-model-plot-1.png" alt="数据根据完全混合模型的预测结果绘制" width="672" />
<p class="caption">
图5.4: 数据根据完全混合模型的预测结果绘制
</p>
</div>
<p>这个模型与数据不太吻合。我们需要一种不同的方法。</p>
</div>
<div id="不混合" class="section level3 hasAnchor" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> 不混合<a href="介绍线性混合效应模型.html#不混合" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>将所有信息混合成一个截距和一个斜率来估计是不合适的。另一种方法是为每个被试拟合单独的线。这意味着每个被试的估计值将完全不受其他被试估计值的影响。换句话说，我们可以分别估计18组单独的截距/斜率对。</p>
<p>这个模型可以通过两种方式实现：(1)为每个被试运行单独的回归或(2)运行混合效应回归。我们将采用后者，这样所有内容都在一个大模型中。我们已经知道了如何做到这一点：我们为<code>Subject</code>因子添加虚拟编码。这个因子有18个水平，所以我们需要17个虚拟编码。幸运的是，R为我们省去了手动创建这17个变量的麻烦。我们只需要在模型中纳入<code>Subject</code>作为预测变量，并将这个分类预测变量与<code>days_deprived</code>进行交互，以允许截距和斜率变化。</p>
<div class="yellowbox">
<p><code>sleep2</code>数据集中的变量<code>Subject</code>是名义变量。我们只是用数字作为标签来保证匿名性，并不意味着被试310比被试309好1点，或者比被试308好2点。确保将其定义为因子变量，而不是作为连续变量包含在内！</p>
<p>我们可以通过多种方式测试某个变量是否为因子变量。其中一种方法是对表格使用<code>summary()</code>函数。</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="介绍线性混合效应模型.html#cb129-1" tabindex="-1"></a>sleep2 <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code></pre></div>
<pre><code>##     Reaction          Days         Subject   days_deprived 
##  Min.   :203.0   Min.   :2.00   308    : 8   Min.   :0.00  
##  1st Qu.:265.2   1st Qu.:3.75   309    : 8   1st Qu.:1.75  
##  Median :303.2   Median :5.50   310    : 8   Median :3.50  
##  Mean   :308.0   Mean   :5.50   330    : 8   Mean   :3.50  
##  3rd Qu.:347.7   3rd Qu.:7.25   331    : 8   3rd Qu.:5.25  
##  Max.   :466.4   Max.   :9.00   332    : 8   Max.   :7.00  
##                                 (Other):96</code></pre>
<p>这里你可以看到它并没有被当做一个数字变量，因为它没给出分布信息(均值等)，而是告诉你在每个水平上有多少个观测值。</p>
<p>你也可以直接测试它：</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="介绍线性混合效应模型.html#cb131-1" tabindex="-1"></a>sleep2 <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Subject) <span class="sc">%&gt;%</span> <span class="fu">is.factor</span>()</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>如果某些变量不是因子变量，你可以使用<code>factor()</code>函数重新定义它，使其变为因子变量。</p>
</div>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="介绍线性混合效应模型.html#cb133-1" tabindex="-1"></a>np_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Reaction <span class="sc">~</span> days_deprived <span class="sc">+</span> Subject <span class="sc">+</span> days_deprived<span class="sc">:</span>Subject,</span>
<span id="cb133-2"><a href="介绍线性混合效应模型.html#cb133-2" tabindex="-1"></a>               <span class="at">data =</span> sleep2)</span>
<span id="cb133-3"><a href="介绍线性混合效应模型.html#cb133-3" tabindex="-1"></a></span>
<span id="cb133-4"><a href="介绍线性混合效应模型.html#cb133-4" tabindex="-1"></a><span class="fu">summary</span>(np_model)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Reaction ~ days_deprived + Subject + days_deprived:Subject, 
##     data = sleep2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -106.521   -8.541    1.143    8.889  128.545 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              288.2175    16.4772  17.492  &lt; 2e-16 ***
## days_deprived             21.6905     3.9388   5.507 2.49e-07 ***
## Subject309               -87.9262    23.3023  -3.773 0.000264 ***
## Subject310               -62.2856    23.3023  -2.673 0.008685 ** 
## Subject330               -14.9533    23.3023  -0.642 0.522422    
## Subject331                 9.9658    23.3023   0.428 0.669740    
## Subject332                27.8157    23.3023   1.194 0.235215    
## Subject333                -2.7581    23.3023  -0.118 0.906000    
## Subject334               -50.2051    23.3023  -2.155 0.033422 *  
## Subject335               -25.3429    23.3023  -1.088 0.279207    
## Subject337                24.6143    23.3023   1.056 0.293187    
## Subject349               -59.2183    23.3023  -2.541 0.012464 *  
## Subject350               -40.2023    23.3023  -1.725 0.087343 .  
## Subject351               -24.2467    23.3023  -1.041 0.300419    
## Subject352                43.0655    23.3023   1.848 0.067321 .  
## Subject369               -21.5040    23.3023  -0.923 0.358154    
## Subject370               -53.3072    23.3023  -2.288 0.024107 *  
## Subject371               -30.4896    23.3023  -1.308 0.193504    
## Subject372                 2.4772    23.3023   0.106 0.915535    
## days_deprived:Subject309 -17.3334     5.5703  -3.112 0.002380 ** 
## days_deprived:Subject310 -17.7915     5.5703  -3.194 0.001839 ** 
## days_deprived:Subject330 -13.6849     5.5703  -2.457 0.015613 *  
## days_deprived:Subject331 -16.8231     5.5703  -3.020 0.003154 ** 
## days_deprived:Subject332 -19.2947     5.5703  -3.464 0.000765 ***
## days_deprived:Subject333 -10.8151     5.5703  -1.942 0.054796 .  
## days_deprived:Subject334  -3.5745     5.5703  -0.642 0.522423    
## days_deprived:Subject335 -25.8995     5.5703  -4.650 9.47e-06 ***
## days_deprived:Subject337   0.7518     5.5703   0.135 0.892895    
## days_deprived:Subject349  -5.2644     5.5703  -0.945 0.346731    
## days_deprived:Subject350   1.6007     5.5703   0.287 0.774382    
## days_deprived:Subject351 -13.1681     5.5703  -2.364 0.019867 *  
## days_deprived:Subject352 -14.4019     5.5703  -2.585 0.011057 *  
## days_deprived:Subject369  -7.8948     5.5703  -1.417 0.159273    
## days_deprived:Subject370  -1.0495     5.5703  -0.188 0.850912    
## days_deprived:Subject371  -9.3443     5.5703  -1.678 0.096334 .  
## days_deprived:Subject372 -10.6041     5.5703  -1.904 0.059613 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 25.53 on 108 degrees of freedom
## Multiple R-squared:  0.849,  Adjusted R-squared:  0.8001 
## F-statistic: 17.35 on 35 and 108 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>这个模型将一个被试(具体来说是被试308)作为基线，并通过偏移量来表示每个被试相对于该基线的差异。在我们之前讨论<a href="交互效应.html#cont-by-cat">连续变量-分类变量交互效应</a>时你已经看过这种方法了。</p>
<div class="purplebox">
<p>回答这些问题(结果保留三位小数)</p>
<ul>
<li>被试308的截距是多少？<input class='webex-solveme nospaces' data-tol='0.001' size='8' data-answer='["288.217466666666"]'/></li>
<li>被试308的斜率是多少？<input class='webex-solveme nospaces' data-tol='0.001' size='8' data-answer='["21.6904952380953"]'/></li>
<li>被试335的截距是多少？<input class='webex-solveme nospaces' data-tol='0.001' size='8' data-answer='["262.874583333333"]'/></li>
<li>被试335的斜率是多少？<input class='webex-solveme nospaces' data-tol='0.001' size='8' data-answer='["-4.20899166666667"]'/></li>
</ul>
<div class="webex-solution">
<button>
答案和解析
</button>
<p>基线被试是308——R中默认按字母顺序排列因子的水平，并选择第一个作为基线。这意味着对于被试308，截距由<code>(Intercept)</code>给出，而斜率由<code>days_deprived</code>给出，因为其他17个虚拟变量对被试308而言都是0。</p>
<p>所有其他被试的回归系数都表示为相对于此基线被试的<em>偏移量</em>。如果我们想计算特定受试者的截距和斜率，只需加上相应的偏移量即可。因此，答案如下：</p>
<ul>
<li><p>被试308的截距: <u>288.217</u></p></li>
<li><p>被试308的斜率: 21.69</p></li>
<li><p>被试355的截距: <code>(Intercept)</code> + <code>Subject335</code> = 288.217 + -25.343 = <u>262.874</u></p></li>
<li><p>被试355的斜率: <code>days_deprived</code> + <code>days_deprived:Subject335</code> = 21.69 + -25.899 = <u>-4.209</u></p></li>
</ul>
</div>
</div>
<p>在“不混合”模型中，没有<em>整个</em>总体截距和斜率的估计；在这种情况下，<code>(Intercept)</code>和<code>days_deprived</code>是被试308的截距和斜率的估计，因为被试308被(随意地)选择为基线被试。为了得到总体的估计值，我们可以引入第二阶段分析，计算各个被试的截距和斜率的平均值。让我们使用模型估计值来计算每个被试的截距和斜率。</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="介绍线性混合效应模型.html#cb135-1" tabindex="-1"></a>all_intercepts <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">coef</span>(np_model)[<span class="st">&quot;(Intercept)&quot;</span>],</span>
<span id="cb135-2"><a href="介绍线性混合效应模型.html#cb135-2" tabindex="-1"></a>                    <span class="fu">coef</span>(np_model)[<span class="dv">3</span><span class="sc">:</span><span class="dv">19</span>] <span class="sc">+</span> <span class="fu">coef</span>(np_model)[<span class="st">&quot;(Intercept)&quot;</span>])</span>
<span id="cb135-3"><a href="介绍线性混合效应模型.html#cb135-3" tabindex="-1"></a></span>
<span id="cb135-4"><a href="介绍线性混合效应模型.html#cb135-4" tabindex="-1"></a>all_slopes  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">coef</span>(np_model)[<span class="st">&quot;days_deprived&quot;</span>],</span>
<span id="cb135-5"><a href="介绍线性混合效应模型.html#cb135-5" tabindex="-1"></a>                 <span class="fu">coef</span>(np_model)[<span class="dv">20</span><span class="sc">:</span><span class="dv">36</span>] <span class="sc">+</span> <span class="fu">coef</span>(np_model)[<span class="st">&quot;days_deprived&quot;</span>])</span>
<span id="cb135-6"><a href="介绍线性混合效应模型.html#cb135-6" tabindex="-1"></a></span>
<span id="cb135-7"><a href="介绍线性混合效应模型.html#cb135-7" tabindex="-1"></a>ids <span class="ot">&lt;-</span> sleep2 <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Subject) <span class="sc">%&gt;%</span> <span class="fu">levels</span>() <span class="sc">%&gt;%</span> <span class="fu">factor</span>()</span>
<span id="cb135-8"><a href="介绍线性混合效应模型.html#cb135-8" tabindex="-1"></a></span>
<span id="cb135-9"><a href="介绍线性混合效应模型.html#cb135-9" tabindex="-1"></a><span class="co"># 用上面提取的数据创建一个tibble</span></span>
<span id="cb135-10"><a href="介绍线性混合效应模型.html#cb135-10" tabindex="-1"></a>np_coef <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Subject =</span> ids,</span>
<span id="cb135-11"><a href="介绍线性混合效应模型.html#cb135-11" tabindex="-1"></a>                  <span class="at">intercept =</span> all_intercepts,</span>
<span id="cb135-12"><a href="介绍线性混合效应模型.html#cb135-12" tabindex="-1"></a>                  <span class="at">slope =</span> all_slopes)</span>
<span id="cb135-13"><a href="介绍线性混合效应模型.html#cb135-13" tabindex="-1"></a></span>
<span id="cb135-14"><a href="介绍线性混合效应模型.html#cb135-14" tabindex="-1"></a>np_coef</span></code></pre></div>
<pre><code>## # A tibble: 18 × 3
##    Subject intercept slope
##    &lt;fct&gt;       &lt;dbl&gt; &lt;dbl&gt;
##  1 308          288. 21.7 
##  2 309          200.  4.36
##  3 310          226.  3.90
##  4 330          273.  8.01
##  5 331          298.  4.87
##  6 332          316.  2.40
##  7 333          285. 10.9 
##  8 334          238. 18.1 
##  9 335          263. -4.21
## 10 337          313. 22.4 
## 11 349          229. 16.4 
## 12 350          248. 23.3 
## 13 351          264.  8.52
## 14 352          331.  7.29
## 15 369          267. 13.8 
## 16 370          235. 20.6 
## 17 371          258. 12.3 
## 18 372          291. 11.1</code></pre>
<p>让我们看看这个模型拟合数据的效果有多好。</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="介绍线性混合效应模型.html#cb137-1" tabindex="-1"></a><span class="fu">ggplot</span>(sleep2, <span class="fu">aes</span>(<span class="at">x =</span> days_deprived, <span class="at">y =</span> Reaction)) <span class="sc">+</span></span>
<span id="cb137-2"><a href="介绍线性混合效应模型.html#cb137-2" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">data =</span> np_coef,</span>
<span id="cb137-3"><a href="介绍线性混合效应模型.html#cb137-3" tabindex="-1"></a>              <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">intercept =</span> intercept,</span>
<span id="cb137-4"><a href="介绍线性混合效应模型.html#cb137-4" tabindex="-1"></a>                            <span class="at">slope =</span> slope),</span>
<span id="cb137-5"><a href="介绍线性混合效应模型.html#cb137-5" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">&#39;blue&#39;</span>) <span class="sc">+</span></span>
<span id="cb137-6"><a href="介绍线性混合效应模型.html#cb137-6" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb137-7"><a href="介绍线性混合效应模型.html#cb137-7" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">7</span>) <span class="sc">+</span></span>
<span id="cb137-8"><a href="介绍线性混合效应模型.html#cb137-8" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Subject) <span class="sc">+</span></span>
<span id="cb137-9"><a href="介绍线性混合效应模型.html#cb137-9" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">&quot;反应时&quot;</span>, <span class="at">x =</span> <span class="st">&quot;睡眠剥夺的天数(0 = 基线)&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:np-model-fits"></span>
<img src="05-%E4%BB%8B%E7%BB%8D%E7%BA%BF%E6%80%A7%E6%B7%B7%E5%90%88%E6%95%88%E5%BA%94%E6%A8%A1%E5%9E%8B_files/figure-html/np-model-fits-1.png" alt="数据根据不混合方法的拟合结果绘制" width="672" />
<p class="caption">
图5.5: 数据根据不混合方法的拟合结果绘制
</p>
</div>
<p>这比完全混合模型要好得多。如果要检验固定斜率为0的原假设，可以用单样本检验。</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="介绍线性混合效应模型.html#cb138-1" tabindex="-1"></a>np_coef <span class="sc">%&gt;%</span> <span class="fu">pull</span>(slope) <span class="sc">%&gt;%</span> <span class="fu">t.test</span>()</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  .
## t = 6.1971, df = 17, p-value = 9.749e-06
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##   7.542244 15.328613
## sample estimates:
## mean of x 
##  11.43543</code></pre>
<p>这告诉我们平均斜率
11.435
显著不等于0,
t(17) = 6.197, <span class="math inline">\(p &lt; .001\)</span>.</p>
</div>
</div>
<div id="使用混合效果模型的部分混合" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> 使用混合效果模型的部分混合<a href="介绍线性混合效应模型.html#使用混合效果模型的部分混合" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>完全混合或不混合方法都不是令人满意的。如果我们能够利用对其他被试的了解来改进对单个被试的估计，那将是可取的。这将有助于更好地区分每个被试的信号(signal)和误差(error)，并提高对总体的可推广性。正如最下面的网页APP所示，当我们有不平衡或缺失的数据时，这变得尤为重要。</p>
<p>在不混合模型中，我们将<code>Subject</code>视为一个<strong>固定因子(fixed factor)</strong>。每对截距和斜率的估计仅由该被试的数据决定。然而，我们对这18个被试本身并不感兴趣；我们更感兴趣的是他们作为具有潜在被试的更大群体的代表。如果你的目标是推广到你感兴趣的群体中的新被试，那么这种被试作为固定效应因子的方法是不够优化的。</p>
<p>部分混合发生在你将一个因子视为随机因子而不是固定因子进行分析时。<strong>随机因子(random factor)</strong>是指其水平被认为代表所有潜在水平的一个真子集(proper subset)。通常情况下，当你数据中的水平是抽样结果，并且你希望推广到超出这些水平的范围时，你会将一个因子视为随机。在这种情况下，我们有18个独特被试(因此有18个<code>Subject</code>因子的水平)，希望能够对潜在被试群体的睡眠剥夺效应做出一些一般性的陈述。</p>
<!-- Just as there are two types of factors---fixed and random---there are -->
<p>一种在分析中包含随机因子的方法是使用线性混合效应模型(linear mixed-effects model)。当你这样做时，每个因子水平(即每个被试)的估计值将受其他水平(即其他被试)信息的影响。与不考虑其他被试估计的情况下为每个被试估计截距和斜率相比，该模型会估计总体的值，并将各个被试的估计值向这些值拉近，这种统计现象称为<code>shrinkage</code>。</p>
<p>下面是多层模型。理解其中的数学原理及其意义非常重要。乍一看似乎很复杂，但实际上这里没有什么是你以前没有见过的。我们将逐步解释一切。</p>
<p><em>第1层:</em></p>
<p><span class="math display">\[\begin{equation}
Y_{sd} = \beta_{0s} + \beta_{1s} X_{sd} + e_{sd}
\end{equation}\]</span></p>
<p><em>第2层:</em></p>
<p><span class="math display">\[\begin{equation}
\beta_{0s} = \gamma_{0} + S_{0s}
\end{equation}\]</span></p>
<p><span class="math display">\[\begin{equation}
\beta_{1s} = \gamma_{1} + S_{1s}
\end{equation}\]</span></p>
<p><em>方差成分(variance components):</em></p>
<p><span class="math display">\[\begin{equation}
\langle S_{0s}, S_{1s} \rangle \sim N\left(\langle 0, 0 \rangle, \mathbf{\Sigma}\right)
\end{equation}\]</span></p>
<p><span class="math display">\[\begin{equation}
\mathbf{\Sigma} = \left(\begin{array}{cc}{\tau_{00}}^2 &amp; \rho\tau_{00}\tau_{11} \\
         \rho\tau_{00}\tau_{11} &amp; {\tau_{11}}^2 \\
         \end{array}\right)
\end{equation}\]</span></p>
<p><span class="math display">\[\begin{equation}
e_{sd} \sim N\left(0, \sigma^2\right)
\end{equation}\]</span></p>
<p>如果你感到迷惑，这里有一个表格，解释了上述方程组中的所有变量。</p>
<table>
<colgroup>
<col width="22%" />
<col width="9%" />
<col width="67%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">变量</th>
<th align="left">类型</th>
<th align="left">描述</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><span class="math inline">\(Y_{sd}\)</span></td>
<td align="left">观测值</td>
<td align="left">被试<span class="math inline">\(s\)</span>在第<span class="math inline">\(d\)</span>天的<code>Reaction</code>值</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(X_{sd}\)</span></td>
<td align="left">观测值</td>
<td align="left">被试<span class="math inline">\(s\)</span>在第<span class="math inline">\(d\)</span>天的<code>days_deprived</code>值(0-7)</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(\beta_{0s}\)</span></td>
<td align="left">派生值</td>
<td align="left">第1层截距参数</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(\beta_{1s}\)</span></td>
<td align="left">派生值</td>
<td align="left">第1层斜率参数</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(e_{sd}\)</span></td>
<td align="left">派生值</td>
<td align="left">被试<span class="math inline">\(s\)</span>在第<span class="math inline">\(d\)</span>天的误差</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(\gamma_0\)</span></td>
<td align="left">固定</td>
<td align="left">总体截距(“gamma”)</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(\gamma_1\)</span></td>
<td align="left">固定</td>
<td align="left">总体斜率(“gamma”)</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(S_{0s}\)</span></td>
<td align="left">派生值</td>
<td align="left">被试<span class="math inline">\(s\)</span>的随机截距(偏移量)</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\(S_{1s}\)</span></td>
<td align="left">派生值</td>
<td align="left">被试<span class="math inline">\(s\)</span>的随机斜率(偏移量)</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(\mathbf{\Sigma}\)</span></td>
<td align="left">随机</td>
<td align="left">方差协方差矩阵</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\({\tau_{00}}^2\)</span></td>
<td align="left">随机</td>
<td align="left">随机截距的方差</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(\rho\)</span></td>
<td align="left">随机</td>
<td align="left">截距和斜率之间的随机相关性</td>
</tr>
<tr class="odd">
<td align="left"><span class="math inline">\({\tau_{11}}^2\)</span></td>
<td align="left">随机</td>
<td align="left">随机斜率的方差</td>
</tr>
<tr class="even">
<td align="left"><span class="math inline">\(\sigma^2\)</span></td>
<td align="left">随机</td>
<td align="left">误差方差</td>
</tr>
</tbody>
</table>
<p>注意，表格的“类型”列包含的内容有<em>固定</em>、<em>随机</em>和<em>派生值</em>。尽管<em>固定</em>和<em>随机</em>是标准术语，但<em>派生值</em>不是；我引入这个术语是为了帮助你理解这些不同变量在模型中的意义，并帮助你区分直接估计的变量和非直接估计的变量。</p>
<p>让我们从模型的第1层方程开始，它表示预测变量和响应变量之间的总体关系。它捕捉了反应时<span class="math inline">\(Y_{sd}\)</span>和睡眠剥夺<span class="math inline">\(X_{sd}\)</span>之间主要关系的函数形式：一条截距为<span class="math inline">\(\beta_{0s}\)</span>和斜率为<span class="math inline">\(\beta_{1s}\)</span>的直线。现在<span class="math inline">\(\beta_{0s}\)</span>和<span class="math inline">\(\beta_{1s}\)</span>使它看起来像完全混合模型，在这种模型中，我们为整个数据集估计一个截距和一个斜率；然而，我们实际上并没有直接估计这些值。相反，我们将<span class="math inline">\(\beta_{0s}\)</span>和<span class="math inline">\(\beta_{1s}\)</span>视为派生值：它们完全由模型第2层的变量定义。</p>
<p>模型的第2层由两个方程定义，表示被试层次的关系。在这里，我们通过固定效应<span class="math inline">\(\gamma_0\)</span>和<em>随机截距</em><span class="math inline">\(S_{0s}\)</span>来定义截距<span class="math inline">\(\beta_{0s}\)</span>；同样地，我们通过固定斜率<span class="math inline">\(\gamma_1\)</span>和<em>随机斜率</em><span class="math inline">\(S_{1s}\)</span>来定义斜率<span class="math inline">\(\beta_{1s}\)</span>。</p>
<p>最后的方程代表模型的<em>方差成分</em>。我们将在下面更详细地讨论这一点。</p>
<p>让我们将第2层方程代入第1层方程，看看以多层方式表示事物的优势。</p>

</div>
</div>
<h3>参考文献<a href="参考文献.html#参考文献" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" line-spacing="2">
<div id="ref-Bates_et_al_2015" class="csl-entry">
Bates, D., Maechler, M., Bolker, B., &amp; Walker, S. (2015). Fitting linear mixed-effects models using lme4. <em><span>Journal of Statistical Software</span></em>, <em>67</em>, 1–48.
</div>
<div id="ref-Belenky_et_al_2003" class="csl-entry">
Belenky, G., Wesensten, N. J., Thorne, D. R., Thomas, M. L., Sing, H. C., Redmond, D. P., Russo, M. B., &amp; Balkin, T. J. (2003). Patterns of performance degradation and restoration during sleep restriction and subsequent recovery: A sleep dose-response study. <em><span>Journal of Sleep Research</span></em>, <em>12</em>(1), 1–12.
</div>
<div id="ref-McElreath_2020" class="csl-entry">
McElreath, R. (2020). <em><span class="nocase">Statistical Rethinking: A Bayesian course with examples in R and STAN</span></em>. CRC Press.
</div>
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  if (t = document.getElementById("webex-total_correct")) {
    t.innerHTML =
      document.getElementsByClassName("webex-correct").length + " of " +
      document.getElementsByClassName("webex-solveme").length + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

window.onload = function() {
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }

  update_total_correct();
}

</script>
<script>
$( document ).ready(function() {
  var cite = ' ';
  var psyteachr = ' <a href="https://psyteachr.github.io/"><img src="images/logos/psyteachr_logo.png" style="height: 31px; color: white;" alt="psyTeachR: Reproducible Research" /></a>';
  var license = ' <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" target="blank"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"></a>';

  $("footer div.row div:eq(1) p").html(
    psyteachr + license + cite
  );
});
</script>

            </section>

          </div>
        </div>
      </div>
<a href="交互效应.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="参考文献.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["CBook.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
